### ISSUE TITLE
Abundance jumps?

### ISSUE THREAD

**Issue by timlichtenberg** [shami-EEG/VULCAN-SPIDER#1]
[plot_atm_chemistry_718259.pdf](https://github.com/shami-EEG/VULCAN-SPIDER/files/3777795/plot_atm_chemistry_718259.pdf)

Hi @shami-EEG,

Three bugs/issues I wonder about:

-  In some timesteps, the mixing ratios jump around like this. Attached are the VULCAN output files from this timestep. In some cells, the CO2 ratio, for example, jumps from 0.407 to 1e-119 and back again. 
-  The Height column has weird values, jumps around similarly.
- There is He, even though the input file has zero He.

Attached all necessary files.

[vulcan_XH_ratios.txt](https://github.com/shami-EEG/VULCAN-SPIDER/files/3777977/vulcan_XH_ratios.txt)
[Timestep_718259.zip](https://github.com/shami-EEG/VULCAN-SPIDER/files/3777804/Timestep_718259.zip)

**Comment by timlichtenberg** [comment]
Also, while we're at it: as discussed earlier it would be good to be able to calculate the *total mass* of each species in the atmosphere. I need this to enforce mass conservation during runtime. What's the most effective way to derive this?

**Comment by shami-EEG** [comment]
The Height column has weird values, jumps around similarly. -- Done
There is He, even though the input file has zero He. -- Done
(Simply adding 'He' into the atom_list, which is the list that the code will actually check)
